# Generated by Django 5.2.17 on 2026-10-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0002_student_email_disciplinerecord'),
        ('tenancy', '0002_school_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'school_class', 'term'], name='enroll_class_term_idx'),
        ),
    ]
