# Generated by Django 5.2.17 on 2026-10-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
