# Generated by Django 5.2.17 on 2026-10-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_removed_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0002_school_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'role'], name='user_school_role_idx'),
        ),
    ]
