# Generated by Django 5.2.17 on 2026-10-02 00:34

from django.db import migrations, models

import tenancy.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, upload_to='school-logos/', validators=[tenancy.validators.validate_logo]),
        ),
    ]
