# Generated by Django 5.2.17 on 2026-10-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='kind',
            field=models.CharField(choices=[('welcome', 'Student welcome'), ('account', 'Account welcome'), ('guardian_link', 'Guardian linked'), ('enrollment', 'Enrollment'), ('absence', 'Absence alert'), ('assessment', 'Assessment published'), ('results', 'Results'), ('discipline', 'Disciplinary notice')], max_length=20),
        ),
    ]
