# Generated by Django 5.2.17 on 2026-10-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_emaillog_kind'),
        ('students', '0002_student_email_disciplinerecord'),
        ('tenancy', '0002_school_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['school', 'student', 'created_at'], name='emaillog_student_idx'),
        ),
    ]
